// AUTH
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER';

// EQLAB
export const EQLAB_LOAD = 'EQLAB_LOAD';
export const EQLAB_UNLOAD = 'EQLAB_UNLOAD';
export const EQLAB_SET_VARS = 'EQLAB_SET_VARS';

// ZONE APP
export const ZONEAPP_LOAD = 'ZONEAPP_LOAD';
export const ZONEAPP_UNLOAD = 'ZONEAPP_UNLOAD';
export const ZONEAPP_SET_ZONELIST = 'ZONEAPP_SET_ZONELIST';
export const ZONEAPP_SELECT_ZONE = 'ZONEAPP_SELECT_ZONE';
export const ZONEAPP_SET_ZONE = 'ZONEAPP_SET_ZONE';
  // SPAWNS
  export const ZONEAPP_SPAWNS_BUILD_SPAWNTREE = 'ZONEAPP_SPAWNS_BUILD_SPAWNTREE';
  export const ZONEAPP_SPAWNS_REBUILD_SPAWNTREE = 'ZONEAPP_SPAWNS_REBUILD_SPAWNTREE';
  export const ZONEAPP_SPAWNS_SET_MODE = 'ZONEAPP_SPAWNS_SET_MODE';
  export const ZONEAPP_SPAWNS_CLEAR_SPAWNTREE = 'ZONEAPP_SPAWNS_CLEAR_SPAWNTREE';
  export const ZONEAPP_SPAWNS_POST_SPAWN2 = 'ZONEAPP_SPAWNS_POST_SPAWN2';
  export const ZONEAPP_SPAWNS_ADD_SPAWN2 = 'ZONEAPP_SPAWNS_ADD_SPAWN2';
  export const ZONEAPP_SPAWNS_GET_SPAWN2TREE = 'ZONEAPP_SPAWNS_GET_SPAWN2TREE';
  export const ZONEAPP_SPAWNS_GET_SPAWNGROUPTREE = 'ZONEAPP_SPAWNS_GET_SPAWNGROUPTREE';
  export const ZONEAPP_SPAWNS_REFRESH_SPAWN2 = 'ZONEAPP_SPAWNS_REFRESH_SPAWN2';
  export const ZONEAPP_SPAWNS_REFRESH_SPAWNGROUP = 'ZONEAPP_SPAWNS_REFRESH_SPAWNGROUP';
  export const ZONEAPP_SPAWNS_REMOVE_SPAWNGROUP = 'ZONEAPP_SPAWNS_REMOVE_SPAWNGROUP';
  export const ZONEAPP_SPAWNS_REMOVE_SPAWN2 = 'ZONEAPP_SPAWNS_REMOVE_SPAWN2';

// NPC APP
export const NPCAPP_LOAD = 'NPCAPP_LOAD';
export const NPCAPP_UNLOAD = 'NPCAPP_UNLOAD';
  // SEARCH
  export const NPCAPP_SEARCH_SET_NPCLIST = 'NPCAPP_SEARCH_SET_NPCLIST';
  export const NPCAPP_SEARCH_SET_NPCID = 'NPCAPP_SEARCH_SET_NPCID';

// SPAWN EDITOR
export const SPAWNEDITOR_LOAD_SPAWN = 'SPAWNEDITOR_LOAD_SPAWN';
export const SPAWNEDITOR_UNLOAD_SPAWN = 'SPAWNEDITOR_UNLOAD_SPAWN';
export const SPAWNEDITOR_GET_SPAWN2 = 'SPAWNEDITOR_GET_SPAWN2';
export const SPAWNEDITOR_REFRESH_SPAWN2 = 'SPAWNEDITOR_REFRESH_SPAWN2';
export const SPAWNEDITOR_DELETE_SPAWN2 = 'SPAWNEDITOR_DELETE_SPAWN2';
export const SPAWNEDITOR_SET_SPAWNGROUP_OPTIONS = 'SPAWNEDITOR_SET_SPAWNGROUP_OPTIONS';
export const SPAWNEDITOR_CHANGE_SPAWNGROUP = 'SPAWNEDITOR_CHANGE_SPAWNGROUP';
export const SPAWNEDITOR_POST_SPAWNGROUP = 'SPAWNEDITOR_POST_SPAWNGROUP';
export const SPAWNEDITOR_DELETE_SPAWNGROUP = 'SPAWNEDITOR_DELETE_SPAWNGROUP';
export const SPAWNEDITOR_SET_NPC_OPTIONS = 'SPAWNEDITOR_SET_NPC_OPTIONS';
export const SPAWNEDITOR_POST_SPAWNENTRY = 'SPAWNEDITOR_POST_SPAWNENTRY';
export const SPAWNEDITOR_DELETE_SPAWNENTRY = 'SPAWNEDITOR_DELETE_SPAWNENTRY';

// NPC EDITOR
export const NPCEDITOR_LOAD_NPC = 'NPCEDITOR_LOAD_NPC';
export const NPCEDITOR_UNLOAD_NPC = 'NPCEDITOR_UNLOAD_NPC';
export const NPCEDITOR_FETCH_NPC = 'NPCEDITOR_FETCH_NPC';
export const NPCEDITOR_PUT_NPC = 'NPCEDITOR_PUT_NPC';
export const NPCEDITOR_UPDATE_NPC = 'NPCEDITOR_UPDATE_NPC';
export const NPCEDITOR_DELETE_NPC = 'NPCEDITOR_DELETE_NPC';
export const NPCEDITOR_SET_FACTION_OPTIONS = 'NPCEDITOR_SET_FACTION_OPTIONS';
export const NPCEDITOR_SET_TINT_OPTIONS = 'NPCEDITOR_SET_TINT_OPTIONS';
export const NPCEDITOR_SET_SPELLSET_OPTIONS = 'NPCEDITOR_SET_SPELLSET_OPTIONS';
export const NPCEDITOR_SET_EFFECTSET_OPTIONS = 'NPCEDITOR_SET_EFFECTSET_OPTIONS';
export const NPCEDITOR_SET_LOOTTABLE_OPTIONS = 'NPCEDITOR_SET_LOOTTABLE_OPTIONS';