export const GENDERS = [
  {value: 0, label: "Male"},
  {value: 1, label: "Female"},
  {value: 2, label: "Monster"}
];

export const PLAYER_CLASSES = [
  {value: 1, bitmask: 1, label: "Warrior"},
  {value: 2, bitmask: 2, label: "Cleric"},
  {value: 3, bitmask: 4, label: "Paladin"},
  {value: 4, bitmask: 8, label: "Ranger"},
  {value: 5, bitmask: 16, label: "Shadow Knight"},
  {value: 6, bitmask: 32, label: "Druid"},
  {value: 7, bitmask: 64, label: "Monk"},
  {value: 8, bitmask: 128, label: "Bard"},
  {value: 9, bitmask: 256, label: "Rogue"},
  {value: 10, bitmask: 512, label: "Shaman"},
  {value: 11, bitmask: 1024, label: "Necromancer"},
  {value: 12, bitmask: 2048, label: "Wizard"},
  {value: 13, bitmask: 4096, label: "Magician"},
  {value: 14, bitmask: 8192, label: "Enchanter"},
  {value: 15, bitmask: 16384, label: "Beastlord"},
  {value: 16, bitmask: 32768, label: "Berserker"}
];

export const NPC_CLASSES = [
  {value: 1, label: "Warrior"},
  {value: 2, label: "Cleric"},
  {value: 3, label: "Paladin"},
  {value: 4, label: "Ranger"},
  {value: 5, label: "Shadow Knight"},
  {value: 6, label: "Druid"},
  {value: 7, label: "Monk"},
  {value: 8, label: "Bard"},
  {value: 9, label: "Rogue"},
  {value: 10, label: "Shaman"},
  {value: 11, label: "Necromancer"},
  {value: 12, label: "Wizard"},
  {value: 13, label: "Magician"},
  {value: 14, label: "Enchanter"},
  {value: 15, label: "Beastlord"},
  {value: 16, label: "Berserker"},
  {value: 20, label: "GM Warrior"},
  {value: 21, label: "GM Cleric"},
  {value: 22, label: "GM Paladin"},
  {value: 23, label: "GM Ranger"},
  {value: 24, label: "GM Shadow Knight"},
  {value: 25, label: "GM Druid"},
  {value: 26, label: "GM Monk"},
  {value: 27, label: "GM Bard"},
  {value: 28, label: "GM Rogue"},
  {value: 29, label: "GM Shaman"},
  {value: 30, label: "GM Necromancer"},
  {value: 31, label: "GM Wizard"},
  {value: 32, label: "GM Magician"},
  {value: 33, label: "GM Enchanter"},
  {value: 34, label: "GM Beastlord"},
  {value: 35, label: "GM Berserker"},
  {value: 40, label: "Banker"},
  {value: 41, label: "Shopkeeper"},
  {value: 59, label: "Discord Merchant"},
  {value: 60, label: "Adventure Recruiter"},
  {value: 61, label: "Adventure Merchant"},
  {value: 63, label: "Tribute Master"},
  {value: 64, label: "Guild Tribute Master"},
  {value: 66, label: "Guild Bank"},
  {value: 67, label: "Radiant Crystal Merchant"},
  {value: 68, label: "Ebon Crystal Merchant"},
  {value: 69, label: "Fellowships"},
  {value: 70, label: "Alternate Currency Merchant"},
  {value: 71, label: "Mercenary Merchant"}
];

export const BODY_TYPES = [
  {value: 1, label: "Humanoid"},
  {value: 2, label: "Lycanthrope"},
  {value: 3, label: "Undead"},
  {value: 4, label: "Giant"},
  {value: 5, label: "Construct"},
  {value: 6, label: "Extraplanar"},
  {value: 7, label: "Magical"},
  {value: 8, label: "Summoned Undead"},
  {value: 9, label: "Raid Giant"},
  {value: 11, label: "No Target"},
  {value: 12, label: "Vampire"},
  {value: 13, label: "Atenha Ra"},
  {value: 14, label: "Greater Akheva"},
  {value: 15, label: "Khati Sha"},
  {value: 16, label: "Seru"},
  {value: 18, label: "Draz Nurakk"},
  {value: 19, label: "Zek"},
  {value: 20, label: "Luggald"},
  {value: 21, label: "Animal"},
  {value: 22, label: "Insect"},
  {value: 23, label: "Monster"},
  {value: 24, label: "Summoned"},
  {value: 25, label: "Plant"},
  {value: 26, label: "Dragon"},
  {value: 27, label: "Summoned2"},
  {value: 28, label: "Summoned3"},
  {value: 30, label: "Velious Dragon"},
  {value: 32, label: "Dragon3"},
  {value: 33, label: "Boxes"},
  {value: 34, label: "Muramite"},
  {value: 60, label: "NoTarget2"},
  {value: 63, label: "Swarm Pet"},
  {value: 66, label: "Invis Man"},
  {value: 67, label: "Special"}
];

export const SKILLS = [
  {value: 0, label: "1H Blunt"},
  {value: 1, label: "1H Slashing"},
  {value: 2, label: "2H Blunt"},
  {value: 3, label: "2H Slashing"},
  {value: 4, label: "Abjuration"},
  {value: 5, label: "Alteration"},
  {value: 6, label: "Apply Poison"},
  {value: 7, label: "Archery"},
  {value: 8, label: "Backstab"},
  {value: 9, label: "Bind Wound"},
  {value: 10, label: "Bash"},
  {value: 11, label: "Block"},
  {value: 12, label: "Brass Instruments"},
  {value: 13, label: "Channeling"},
  {value: 14, label: "Conjuration"},
  {value: 15, label: "Defense"},
  {value: 16, label: "Disarm"},
  {value: 17, label: "Disarm Traps"},
  {value: 18, label: "Divination"},
  {value: 19, label: "Dodge"},
  {value: 20, label: "Double Attack"},
  {value: 21, label: "Dragon Punch"},
  {value: 22, label: "Dual Wield"},
  {value: 23, label: "Eagle Strike"},
  {value: 24, label: "Evocation"},
  {value: 25, label: "Feign Death"},
  {value: 26, label: "Flying Kick"},
  {value: 27, label: "Forage"},
  {value: 28, label: "Hand to Hand"},
  {value: 29, label: "Hide"},
  {value: 30, label: "Kick"},
  {value: 31, label: "Meditate"},
  {value: 32, label: "Mend"},
  {value: 33, label: "Offense"},
  {value: 34, label: "Parry"},
  {value: 35, label: "Pick Lock"},
  {value: 36, label: "Piercing"},
  {value: 37, label: "Riposte"},
  {value: 38, label: "Round Kick"},
  {value: 39, label: "Safe Fall"},
  {value: 40, label: "Sense Heading"},
  {value: 41, label: "Singing"},
  {value: 42, label: "Sneak"},
  {value: 43, label: "Specialize Abjuration"},
  {value: 44, label: "Specialize Alteration"},
  {value: 45, label: "Specialize Conjuration"},
  {value: 46, label: "Specialize Divination"},
  {value: 47, label: "Specialize Evocation"},
  {value: 48, label: "Pick Pockets"},
  {value: 49, label: "Stringed Instruments"},
  {value: 50, label: "Swimming"},
  {value: 51, label: "Throwing"},
  {value: 52, label: "Tiger Claw"},
  {value: 53, label: "Tracking"},
  {value: 54, label: "Wind Instruments"},
  {value: 55, label: "Fishing"},
  {value: 56, label: "Make Poison"},
  {value: 57, label: "Tinkering"},
  {value: 58, label: "Research"},
  {value: 59, label: "Alchemy"},
  {value: 60, label: "Baking"},
  {value: 61, label: "Tailoring"},
  {value: 62, label: "Sense Traps"},
  {value: 63, label: "Blacksmithing"},
  {value: 64, label: "Fletching"},
  {value: 65, label: "Brewing"},
  {value: 66, label: "Alcohol Tolerance"},
  {value: 67, label: "Begging"},
  {value: 68, label: "Jewelry Making"},
  {value: 69, label: "Pottery"},
  {value: 70, label: "Percussion Instruments"},
  {value: 71, label: "Intimidation"},
  {value: 72, label: "Berserking"},
  {value: 73, label: "Taunt"},
  {value: 74, label: "Frenzy"},
  {value: 75, label: "Remove Traps"},
  {value: 76, label: "Triple Attack"},
  {value: 77, label: "2H Piercing"}
];

export const MELEE_ATTACK_SKILLS = [
  {value: 0, label: "1H Blunt"},
  {value: 1, label: "1H Slashing"},
  {value: 2, label: "2H Blunt"},
  {value: 3, label: "2H Slashing"},
  {value: 8, label: "Backstab"},
  {value: 10, label: "Bash"},
  {value: 21, label: "Dragon Punch"},
  {value: 23, label: "Eagle Strike"},
  {value: 26, label: "Flying Kick"},
  {value: 28, label: "Hand to Hand"},
  {value: 30, label: "Kick"},
  {value: 36, label: "Piercing"},
  {value: 38, label: "Round Kick"},
  {value: 52, label: "Tiger Claw"},
  {value: 74, label: "Frenzy"},
  {value: 77, label: "2H Piercing"}
];

export const RANGE_ATTACK_SKILLS = [
  {value: 7, label: "Archery"},
  {value: 51, label: "Throwing"}
];

export const NPC_SPELL_TYPES = {
  1: "Nuke",
  2: "Heal",
  4: "Root",
  8: "Buff",
  16: "Escape",
  32: "Pet",
  64: "Lifetap",
  128: "Snare",
  256: "DoT",
  512: "Dispel",
  1024: "InCombatBuff",
  2048: "Mez",
  4096: "Charm",
  8192: "Slow",
  16384: "Debuff",
  32768: "Cure",
  65536: "Resurrect",
  131072: "HateReduction",
  262144: "InCombatBuffSong",
  524288: "OutOfCombatBuffSong",
  1048576: "PreCombatBuff",
  2097152: "PreCombatBuffSong"
}